version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
  server:
    env_file:
      - .env
    build: ./
    depends_on:
      - postgres
    ports:
      - 8080:8080



volumes:
  postgres_data:
